version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "chore(deps)"
  
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "ci(deps)"
